PREFIXE=.
LECTURE_AUTO_STATUS=non
TELECHARGER_AUTO_STATUS=non
NOM_BOT=FADEL-DIOUF
LIENS_MENU=https://telegra.ph/file/7113ddc85a26a69a7a437.jpg
PM_PERMIT=non
MODE_PUBLIC=oui
ETAT=1
SESSION_ID=HACKING-MD;;;=>eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNEZqcWRvYXJjUTZGeFN1Z3FsRWI2ZFpCS05iZmp1VnZvU0FQRy82VmFuTT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSEVZSmZzd2I4ZW5HVEJmNEExSjJ1ekkzZWtKanRMb2EvNHdSaUtra2kyST0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJHTTc5ZjArd2lSb21WT2RjdUMvYnM4Rmc0V2o5b1FrSzV3SE4yN1BQUjNZPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJpZXpOTm1GZjZzRExZN2FNd0REU2VrREk0czdqUVNsNUVEeTlNTktpZVEwPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IndHemVXNlBMZ01zQlhLSk5GMTBOZUxGRzRlVWN4QmFQSFEzR3U0UTd6V1U9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJDQ05BNmRXUlBjS3F5QVJrUTdOYU5GY1BQMS95MzJjZVd4bHhNdW4wMVU9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiK00yL0VVSTFSTU9QemhKaWpZdjNzM282UFV3K2NIc2REbzBXUWFBTkowWT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiK0dBSnljSjRBYklJRytjVEllcVM4UnFHcUVJbUtWL290aWYwKytCOTlYYz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkdtemZhSzNmTkc3dFh2YkE0RkxQdmdOVFlTbVp1OWcveXRnTm1kaVBLQXpzMTR2ZU80QWdvU3Q4RkY1NzdUbnFGdUZYMU9YNFFtYTFHWFNYdS9aT2lBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTkwLCJhZHZTZWNyZXRLZXkiOiIvS3Z4N3g1NWNuck12Zkw1ZnJFSWcvRkE4cWhPTUFQcTlZa2dlNEdqRmF3PSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJiblhINmRsNVJKZWNvbnRFeFZrMzlBIiwicGhvbmVJZCI6ImJjNTlhNWUyLTljYjctNDUxNi04ZjJmLTQyYzJlYjI5ZmM1MiIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI0RXhKbkd0b2o2aWpoTVAxRHNRZjlYMjdCNk09In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiblRWWHE2OWYrK3lEWTZjQWZaeHVEcGZwd0h3PSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6Ik1XMlZEUTNFIiwibWUiOnsiaWQiOiIyMjE3NzgxNTA2OTA6MzBAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoi8J2QhfCdmqvwnZCD8J2atfCdkIsg8J2Qg/CdmrDwnZqv8J2QlPCdkIUg8J2atPCdmrXwnZq+8J2au/CdmqvwnZCG8J2atSJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTURKeTdFRkVOcU5qTG9HR0FFZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoiSFhyNUFlNkIyWHk1eUZFaFBmL050N29uSlFwK29udW9PVkErNWpiNHlCQT0iLCJhY2NvdW50U2lnbmF0dXJlIjoiK3FsZm04ckpoZDhSOVFSYnhCS1NQNU8wU0NlZEkrcXZZaFZFWWxkS2F4TjBlMkJuYmtWRE83bnBHeHFreUtGUU1DenBhcU9LNU9KczN5TEgwekFSQUE9PSIsImRldmljZVNpZ25hdHVyZSI6ImZvWkIrMVEweWpTYURqblRXb1R6TWxWdm9nNTVQTWhzUnJTbGFkaGp2ZHNiZWh1MnJsSzRUUDk4THdZbXdRZUZxaVd5VnliT0tHbU9pK1I5dnFZemlnPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjIxNzc4MTUwNjkwOjMwQHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQlIxNitRSHVnZGw4dWNoUklUMy96YmU2SnlVS2ZxSjdxRGxRUHVZMitNZ1EifX1dLCJwbGF0Zm9ybSI6InNtYmEiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MzI0NDU5Mjl9
NOM_OWNER=FADEL DIOUF
NUMERO_OWNER=221778150690
WARN_COUNT=3
STARTING_BOT_MESSAGE=oui
ANTI_VUE_UNIQUE=non
PM_CHATBOT=non
HEROKU=non
DATABASE_URL=postgresql://hacking_user:scLwto0JRQeGVNehhkiSS14W9d2WMRkz@dpg-cr66l2ij1k6c739cgqng-a.oregon-postgres.render.com/hacking
ANTI_COMMAND_SPAM=non
name: Node.js CI

on:

push:

branches:

- main

pull_request:

branches:

- main

jobs:

build:

runs-on: ubuntu-latest

strategy:

matrix:

node-version: [20.x]

steps:

- name: Checkout repository

uses: actions/checkout@v3

- name: Set up Node.js

uses: actions/setup-node@v3

with:

node-version: ${{ matrix.node-version }}

- name: Install dependencies

run: npm install

- name: Start application

run: npm start
